//! Double-click on Muya's own title bar (the header drawn in the webview — the window
//! uses an overlay title bar, so macOS never sees these clicks) does what the operator
//! chose in System Settings › Desktop & Dock › "Double-click a window's title bar to":
//! zoom (the default), fill, minimize, or nothing.

use std::process::Command;
use std::sync::OnceLock;

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
enum Action {
    Zoom,
    Minimize,
    Nothing,
}

/// `defaults read -g AppleActionOnDoubleClick`: "Maximize"/"Fill" (or unset) zoom,
/// "Minimize" minimizes, "None" does nothing.
fn parse_action(value: &str) -> Action {
    match value.trim() {
        "Minimize" => Action::Minimize,
        "None" | "Do Nothing" => Action::Nothing,
        _ => Action::Zoom,
    }
}

fn action() -> Action {
    // Read once per run: it is a rarely changed system preference, and a process spawn
    // per double-click would add visible latency.
    static ACTION: OnceLock<Action> = OnceLock::new();
    *ACTION.get_or_init(|| {
        Command::new("/usr/bin/defaults")
            .args(["read", "-g", "AppleActionOnDoubleClick"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| parse_action(&String::from_utf8_lossy(&o.stdout)))
            .unwrap_or(Action::Zoom)
    })
}

#[tauri::command]
pub fn title_bar_double_click(window: tauri::WebviewWindow) -> Result<(), String> {
    let r = match action() {
        Action::Nothing => Ok(()),
        Action::Minimize => window.minimize(),
        Action::Zoom => {
            if window.is_fullscreen().unwrap_or(false) {
                return Ok(()); // full screen has no title bar to zoom from
            }
            if window.is_maximized().unwrap_or(false) {
                window.unmaximize()
            } else {
                window.maximize()
            }
        }
    };
    r.map_err(|e| e.to_string())
}

/// Open the bundled third-party license notices (THIRD_PARTY_LICENSES.txt, generated by
/// tools/third-party-notices.mjs) in TextEdit — Settings › Open-source licenses.
#[tauri::command]
pub fn open_third_party_licenses(app: tauri::AppHandle) -> Result<(), String> {
    use tauri::Manager;
    let path = app
        .path()
        .resolve("THIRD_PARTY_LICENSES.txt", tauri::path::BaseDirectory::Resource)
        .map_err(|e| e.to_string())?;
    if !path.is_file() {
        return Err(format!("license notices not found at {}", path.display()));
    }
    Command::new("/usr/bin/open")
        .arg("-e") // TextEdit: a plain read-only-ish viewer that is always there
        .arg(&path)
        .status()
        .map_err(|e| e.to_string())
        .and_then(|s| if s.success() { Ok(()) } else { Err(format!("open exited with {s}")) })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reads_the_macos_preference_values() {
        assert_eq!(parse_action("Maximize\n"), Action::Zoom);
        assert_eq!(parse_action("Fill"), Action::Zoom);
        assert_eq!(parse_action(""), Action::Zoom);
        assert_eq!(parse_action("Minimize\n"), Action::Minimize);
        assert_eq!(parse_action("None"), Action::Nothing);
    }
}
